### ISSUE TITLE
template.xhtml is missing in hello1-rlc

### ISSUE THREAD

**Issue by MasoodFallahpoor** [eclipse-ee4j/jakartaee-tutorial-examples#16]
Pages greeting.xhtml and response.xhtml of hello1-rlc example are using a template called template.xhtml but template.xhtml is missing.

**Comment by bshannon** [comment]
(I'm not a JSF expert.)

There's several template.xhtml files under the contracts directory, which seems to be configured by WEB-INF/faces-config.xml.  Are you saying that they're not being found when you run the application?

**Comment by MasoodFallahpoor** [comment]
My bad. Actually the application runs successfully but IntelliJ IDEA gives a 'Cannot resolve symbol' error.
